version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "8954:8954"
    depends_on:
      - api
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules

  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      - NODE_ENV=development
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=time_db
    volumes:
      - ./api:/app
      - /app/node_modules

  mysql:
    image: mysql:8.0.35
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=time_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpass
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
      - ADMINER_DESIGN=pepa-linha

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - mysql

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

volumes:
  mysql-data:
  portainer-data:

networks:
  default:
    driver: bridge