version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./images:/images
      - ./data:/data
    environment:
      - FLASK_ENV=development
    restart: always