version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - images_volume:/images:rw
      - data_volume:/data:rw
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: always

volumes:
  images_volume:
    external: true
  data_volume:
    external: true