name: Проверка Синтаксиса

on:
  push:
    branches: [ "Practice7" ]
  pull_request:
    branches: [ "Practice7" ]

jobs:
  syntax:
    runs-on: ubuntu-latest

    steps:
    - name: Проверка репозитория
      uses: actions/checkout@v3

    - name: Установка cpp-check
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck

    - name: Проверка кода на ошибки
      run: |
        cppcheck --enable=warning,style,performance \
        --suppress=missingInclude \
        --language=c++ \
        --std=c++17 \
        controllers/* models/* utils/* views/*

    - name: Вывод результатов
      run: |
        echo "Проверка синтаксиса завершена. Если выше нет ошибок - код синтаксически корректен."